name: Disparar Tarefa Diária de Envio

on:
  schedule:
    # Roda todos os dias às 12:00 UTC (09:00 no Horário de Brasília)
    - cron: '0 12 * * *'
  workflow_dispatch: # Permite rodar manualmente pela interface do GitHub

jobs:
  trigger-task:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar o endpoint do backend para disparar a tarefa
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
          ${{ secrets.BACKEND_URL }}/trigger-daily-task
